### ISSUE TITLE
Ajaxed-jquery class datatable

### ISSUE THREAD

**Issue by mangius** [damsfx/asp-ajaxed#1]
Ajaxed is a very useful and simple framework for old asp programming, and make a version that support jquery is a very very good idea.
I wrote several small web application with ajaxed, but when i attempt to migrate to version 2.1.2 i found many problem with datatable class. Have you planned to rewrite datatable.js with jquery version? Thanks

**Comment by damsfx** [comment]
Issue fixed in v2.1.3 release.
See : https://github.com/damsfx/asp-ajaxed/tree/release-2.1.3
